version: "3"
services:
  db:
    image: "postgres"
    container_name: "dbpostgressql"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${USUARIO}
      POSTGRES_PASSWORD: ${PASSWD}
      POSTGRES_DB: ${DB}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - db-datos:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-datos:/var/lib/pgadmin
    links:
      - "db:pgsql-server"
    depends_on:
      - db
volumes:
  db-datos:
  pgadmin-datos: