POST http://localhost:3000/api/usuarios/registrar
Content-Type: application/json

{
    "correo": "correo2@correo.correo",
    "passwd": "Passwd2",
    "nombreCompleto": "usuario2",
    "rol": "administrador"
}