POST http://localhost:3000/api/usuarios/registrar
Content-Type: application/json

{
    "correo": "correo5@correo.correo",
    "passwd": "Passwd5",
    "nombreCompleto": "usuario5",
    "idCripto": "be45d74b-5ffe-4b28-8bbd-96f051fa0385"
}