POST http://localhost:3000/api/nft
Content-Type: application/json

{
    "nombre": "nft2",
    "img": "img2",
    "idUsuarioCreador": "84ac119a-63cb-4a80-9749-d3138fcd512b",
    "fechaCreacion": "2023-01-01",
    "idUsuarioDueno": "84ac119a-63cb-4a80-9749-d3138fcd512b"
}