POST http://localhost:3000/api/nft
Content-Type: application/json

{
    "nombre": "nft3",
    "img": "img3",
    "precio": 5000,
    "idUsuarioCreador": "6ad5e6ca-cf74-4434-a211-caf210487561",
    "fechaCreacion": "2023-01-01",
    "idUsuarioDueno": "6ad5e6ca-cf74-4434-a211-caf210487561"
}