POST http://localhost:3000/api/productos
Content-Type: application/json

{
    "nombre": "nombre",
    "precio": 5,
    "descripcion": "descripcion",
    "stock": 5,
    "propiedades": ["propiedad1", "propiedad2"],
    "tipo": "objeto1"
}